services:
  next:
    build:
      dockerfile: docker/next/Dockerfile
    depends_on:
      - mongo
    networks:
      - kobros
    ports:
      - 3050:3050
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    networks:
      - kobros
networks:
  kobros:
    driver: bridge
volumes:
  mongodata:
